

import 'package:dto/event.dart';
import 'users.dart';


List<Event> events = [
  Event(
    adresse: '789 Boulevard des Rires',
    theme: 'Barbecue estival',
    nom: 'Fête de Quartier',
    host: users[2],
    invited: [users[0].email, users[1].email, users[3].email],
    present: [users[6].email, users[5].email, users[4].email],
    absent: [users[8].email, users[9].email],
    date: DateTime.now(),
    brings: ["chips", "soda", "bière"],
  ),
  Event(
    adresse: '123 Avenue de la Musique',
    theme: 'Soirée Karaoké',
    nom: 'Nuit en Chansons',
    host: users[5],
    invited: [users[2].email, users[4].email, users[6].email],
    present: [users[1].email, users[3].email, users[8].email],
    absent: [users[0].email, users[7].email],
    date: DateTime.now().add(Duration(days: 7)),
    brings: ["microphone", "snacks", "drinks"],
  ),
  Event(
    adresse: '456 Rue des Jeux',
    theme: 'Soirée Jeux de Société',
    nom: 'Game Night',
    host: users[1],
    invited: [users[0].email, users[2].email, users[3].email],
    present: [users[5].email, users[7].email, users[9].email],
    absent: [users[4].email, users[6].email],
    date: DateTime.now().add(Duration(days: 14)),
    brings: ["board games", "popcorn", "soft drinks"],
  ),
  Event(
    adresse: '567 Avenue des Films',
    theme: 'Cinéma en plein air',
    nom: 'Movie Night',
    host: users[7],
    invited: [users[1].email, users[4].email, users[6].email],
    present: [users[0].email, users[2].email, users[5].email],
    absent: [users[3].email, users[8].email],
    date: DateTime.now().add(Duration(days: 21)),
    brings: ["blankets", "popcorn", "favorite movies"],
  ),
  Event(
    adresse: '890 Rue du Déguisement',
    theme: 'Soirée Costumée',
    nom: 'Masquerade',
    host: users[3],
    invited: [users[0].email, users[2].email, users[5].email],
    present: [users[1].email, users[4].email, users[9].email],
    absent: [users[6].email, users[7].email],
    date: DateTime.now().add(Duration(days: 30)),
    brings: ["costumes", "music", "snacks"],
  ),
  Event(
    adresse: '234 Boulevard de la Danse',
    theme: 'Fiesta Latino',
    nom: 'Salsa Night',
    host: users[9],
    invited: [users[1].email, users[3].email, users[6].email],
    present: [users[0].email, users[2].email, users[5].email],
    absent: [users[4].email, users[7].email],
    date: DateTime.now().add(Duration(days: 35)),
    brings: ["maracas", "tacos", "mojitos"],
  ),
  Event(
    adresse: '678 Avenue de l\'Art',
    theme: 'Soirée Peinture',
    nom: 'Artistic Evening',
    host: users[6],
    invited: [users[0].email, users[2].email, users[4].email],
    present: [users[1].email, users[5].email, users[8].email],
    absent: [users[3].email, users[7].email],
    date: DateTime.now().add(Duration(days: 42)),
    brings: ["paints", "canvases", "snacks"],
  ),
  Event(
    adresse: '345 Rue du Suspense',
    theme: 'Soirée Mystère',
    nom: 'Mystery Night',
    host: users[4],
    invited: [users[1].email, users[3].email, users[5].email],
    present: [users[0].email, users[2].email, users[7].email],
    absent: [users[6].email, users[8].email],
    date: DateTime.now().add(Duration(days: 49)),
    brings: ["mystery games", "flashlights", "snacks"],
  ),
  Event(
    adresse: '901 Avenue de la Détente',
    theme: 'Spa Party',
    nom: 'Relaxation Day',
    host: users[8],
    invited: [users[0].email, users[2].email, users[6].email],
    present: [users[1].email, users[4].email, users[9].email],
    absent: [users[3].email, users[5].email],
    date: DateTime.now().add(Duration(days: 56)),
    brings: ["face masks", "candles", "snacks"],
  ),
  Event(
    adresse: '789 Boulevard des Rires',
    theme: 'Soirée Camping',
    nom: 'Campfire Gathering',
    host: users[0],
    invited: [users[1].email, users[3].email, users[7].email],
    present: [users[2].email, users[4].email, users[6].email],
    absent: [users[5].email, users[8].email],
    date: DateTime.now().add(Duration(days: 63)),
    brings: ["tents", "marshmallows", "camping chairs"],
  ),
];

